{
  "openapi": "3.0.0",
  "info": {
    "title": "Task.io API",
    "description": "API task.io",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "/v1"
    }
  ],
  "paths": {
    "/users": {
      "get": {
        "summary": "Busca de usuários",
        "description": "Essa rota será responsável por buscar todos os usuários cadastrados.",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "cookieAuth": []
          }
        ],
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Nenhum usuário encontrado"
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/user"
                  }
                },
                "examples": {
                  "userList": {
                    "value": {
                      "users": [
                        {
                          "id": 1,
                          "name": "Pedro",
                          "username": "pedro",
                          "password": "$2a$12$JCeONEkxkfYFkkpiUg2YluzTZz7iSowkslrxPulT2K5MlgjWGiOta",
                          "createdAt": "2024-05-25T16:18:09.442Z",
                          "updatedAt": "2024-05-25T16:18:09.442Z"
                        },
                        {
                          "id": 2,
                          "name": "Marcus",
                          "username": "marcus",
                          "password": "$2a$12$iW4UnIp3EXYDieAC/7dx2OXqljyCVytJ286vursXQML6IZzvJyF7K",
                          "createdAt": "2024-05-25T16:14:16.501Z",
                          "updatedAt": "2024-05-29T02:00:13.629Z"
                        },
                        {
                          "id": 3,
                          "name": "Lucas",
                          "username": "lucas",
                          "password": "$2nb$12$iWa3EXYD2eAC/7dx2-2ljyadCVytad286vunXQv21aL6dZzvJfaV2",
                          "createdAt": "2024-05-26T16:14:16.501Z",
                          "updatedAt": "2024-05-29T07:00:13.629Z"
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "summary": "Cadastro de usuário",
        "description": "Essa rota será responsável por cadastrar um novo usuário.",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "cookieAuth": []
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "items": {
                  "$ref": "#/components/schemas/user"
                }
              },
              "examples": {
                "user": {
                  "value": {
                    "name": "John Doe",
                    "username": "johndoe",
                    "password": "secretpassword"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "400": {
            "description": "Usuário já existente"
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "$ref": "#/components/schemas/user"
                  }
                },
                "examples": {
                  "user": {
                    "value": {
                      "user": {
                        "id": 1,
                        "name": "John Doe",
                        "username": "johndoe",
                        "password": "$2a$12$dPgLyqtAaR8KHN19VD7lcuZaLE1cJUn8OH13tv8DYRlp.oJZLMZVa",
                        "updatedAt": "2024-05-29T02:23:43.087Z",
                        "createdAt": "2024-05-29T02:23:43.087Z"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/users/{userId}": {
      "get": {
        "summary": "Busca de usuário por ID",
        "description": "Essa rota será responsável por buscar o usuário especificado por ID.",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "cookieAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "userId",
            "schema": {
              "type": "integer"
            },
            "description": "ID do usuário para busca",
            "required": true
          }
        ],
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Nenhum usuário encontrado"
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "$ref": "#/components/schemas/user"
                  }
                },
                "examples": {
                  "user": {
                    "value": {
                      "user": {
                        "id": 1,
                        "name": "John Doe",
                        "username": "johndoe",
                        "password": "$2a$12$dPgLyqtAaR8KHN19VD7lcuZaLE1cJUn8OH13tv8DYRlp.oJZLMZVa",
                        "updatedAt": "2024-05-28T02:20:45.087Z",
                        "createdAt": "2024-05-29T02:23:43.087Z"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      },
      "put": {
        "summary": "Atualização de usuário por ID",
        "description": "Esta rota é responsável por atualizar os dados do usuário especificado por ID.",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "cookieAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "userId",
            "schema": {
              "type": "integer"
            },
            "description": "ID do usuário para atualização",
            "required": true
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "items": {
                  "$ref": "#/components/schemas/user"
                }
              },
              "examples": {
                "user": {
                  "value": {
                    "name": "John Doe",
                    "username": "johndoe",
                    "oldPassword": "oldsecretpassword",
                    "newPassword": "newsecretpassword"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Nenhum usuário encontrado"
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "$ref": "#/components/schemas/user"
                  }
                },
                "examples": {
                  "user": {
                    "value": {
                      "user": {
                        "id": 1,
                        "name": "John Doe",
                        "username": "johndoe",
                        "password": "$2a$12$dPgLyqtAaR8KHN19VD7lcuZaLE1cJUn8OH13tv8DYRlp.oJZLMZVa",
                        "updatedAt": "2024-05-29T02:23:43.087Z",
                        "createdAt": "2024-05-29T02:23:43.087Z"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "summary": "Exclusão de usuário por ID",
        "description": "Esta rota é responsável por excluir o usuário especificado por ID.",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "cookieAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "userId",
            "schema": {
              "type": "integer"
            },
            "description": "ID do usuário para exclusão",
            "required": true
          }
        ],
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Nenhum usuário encontrado"
          },
          "204": {
            "description": "No Content"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "user": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "name": {
            "type": "string"
          },
          "username": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "createdAt": {
            "type": "string"
          },
          "updatedAt": {
            "type": "string"
          }
        }
      }
    },
    "securitySchemes": {
      "cookieAuth": {
        "type": "apiKey",
        "in": "cookie",
        "name": "access_token"
      }
    }
  }
}